13911 create a restful service version for status report
konturio/geocint-runner pull request #21
Opened 2022-12-22 17:42 UTC by saricicekibrahim

2022-12-24 16:57 UTC, Zkir requested changes

2022-12-24 16:57 UTC, Zkir commented on report/app.js
> +                  let failedFile = "./logs/" + rec[recLog] + "/" + rec[recEventName] + "/" + logFileName
it seems that this is wrong.
it is assumed that app.js is run from /home/user-name/geocint  folder, but it cannot be so.
This folder itself is created by geocint runner an may not exist before the first run.

App should find proper path to logs, when run from geocint-runner folder.

2022-12-24 16:57 UTC, Zkir commented on report/reportFiles/script.js
> +    var url = "http://" + window.location.hostname + '/statusReport';
we had to change is line to var 
`url = "http://localhost:5000/statusReport";`

not sure is it important or not.

2022-12-25 01:19 UTC, Komzpa commented
I am concerned about this development: somehow we ended up with a new backend service skipping general architecture review and having a very misplaced code. 

The svg report generator is profile_make and the HTML report is also expected to be placed there, if developed as static generator.

If we want to do this not in a static fashion but rather as a web app, we need to utilize our frontend/backend framework and rather make it a custom disaster ninja app, with proper data routing. 

This code has to be re-done in either of above ways. Current architecture of the above is not acceptable for long term management.

2022-12-28 18:03 UTC, saricicekibrahim commented
no restful service needed

2022-12-28 18:03 UTC, closed without merging